# Nama Project : Memprediksi Kualitas Susu (Low, Medium, High) Berdasarkan Dataset "milknew.csv" menggunakan Algoritma Naive Bayes

## Nama : Rifai Nugroho
## NIM : 10121295
## Kelas : IF8
## Asal Kampus : Universitas Komputer Indonesia (Kota Bandung)

In [ ]:
import numpy as np
import pandas as pd

from google.colab import files
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
uploaded=files.upload()

Saving milknew.csv to milknew (1).csv


In [ ]:
dataset = pd.read_csv('milknew.csv')
dataset.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   object 
dtypes: float64(1), int64(6), object(1)
memory usage: 66.3+ KB


In [ ]:
dataset.empty

False

In [ ]:
en = LabelEncoder()
dataset['pH'] = en.fit_transform(dataset['pH'])
dataset['Grade'] = en.fit_transform(dataset['Grade'])
dataset.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour  Grade
0   7          35      1     0     1          0     254      0
1   7          36      0     1     0          1     253      0
2  12          70      1     1     1          1     246      1
3  15          34      1     1     0          1     255      1
4   7          37      0     0     0          0     255      2

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pH          1059 non-null   int64
 1   Temprature  1059 non-null   int64
 2   Taste       1059 non-null   int64
 3   Odor        1059 non-null   int64
 4   Fat         1059 non-null   int64
 5   Turbidity   1059 non-null   int64
 6   Colour      1059 non-null   int64
 7   Grade       1059 non-null   int64
dtypes: int64(8)
memory usage: 66.3 KB


In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
x

array([[  7,  35,   1, ...,   1,   0, 254],
       [  7,  36,   0, ...,   0,   1, 253],
       [ 12,  70,   1, ...,   1,   1, 246],
       ...,
       [  0,  40,   1, ...,   1,   1, 255],
       [  9,  43,   1, ...,   1,   0, 250],
       [ 13,  55,   0, ...,   1,   1, 255]])

In [ ]:
y

array([0, 0, 1, ..., 1, 0, 1])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

x_train =  847
x_test =  212
y_train =  847
y_test =  212


In [ ]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[ 0.39165197, -0.41330182,  0.91504655, ...,  0.6803433 ,
        -0.99411413, -1.61267828],
       [-0.15172103,  0.09729713, -1.09284057, ..., -1.46984617,
         1.00592071, -0.43999756],
       [ 0.39165197,  0.09729713,  0.91504655, ...,  0.6803433 ,
        -0.99411413, -1.61267828],
       ...,
       [-0.42340753, -0.82178098, -1.09284057, ...,  0.6803433 ,
        -0.99411413,  0.73268316],
       [-0.15172103,  0.60789609, -1.09284057, ..., -1.46984617,
         1.00592071, -0.43999756],
       [ 0.39165197,  0.09729713,  0.91504655, ...,  0.6803433 ,
        -0.99411413, -1.61267828]])

In [ ]:
x_test

array([[-0.15172103, -0.41330182,  0.91504655, ...,  0.6803433 ,
         1.00592071,  0.73268316],
       [-1.78184004,  1.62909399, -1.09284057, ...,  0.6803433 ,
         1.00592071, -0.43999756],
       [ 1.75008448, -0.10694245,  0.91504655, ...,  0.6803433 ,
         1.00592071, -0.43999756],
       ...,
       [ 0.39165197, -0.31118203, -1.09284057, ..., -1.46984617,
        -0.99411413,  0.73268316],
       [-0.42340753, -0.82178098, -1.09284057, ...,  0.6803433 ,
        -0.99411413,  0.26361087],
       [-0.15172103,  0.09729713, -1.09284057, ...,  0.6803433 ,
         1.00592071, -0.43999756]])

In [ ]:
y_train

array([2, 2, 0, 1, 1, 0, 2, 1, 2, 2, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 2, 1,
       2, 1, 2, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 2, 0, 2, 2,
       1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 1, 0, 2, 1, 1, 1,
       2, 0, 2, 0, 2, 0, 1, 1, 1, 2, 0, 2, 1, 1, 2, 0, 2, 2, 0, 0, 2, 1,
       2, 1, 0, 2, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 1, 1,
       2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1,
       1, 1, 0, 1, 2, 0, 2, 2, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 1, 1, 0,
       1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 0,
       0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2, 2, 1, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 0, 0,
       2, 2, 0, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 1,
       2, 1, 0, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 0, 2, 0, 2, 2, 2, 1, 1, 0,
       2, 1, 0, 2, 1, 2, 2, 1, 0, 0, 0, 0, 0, 2, 1,

In [ ]:
y_test

array([0, 1, 1, 2, 2, 1, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2, 2, 1, 2,
       0, 2, 2, 2, 1, 0, 1, 1, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2,
       0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1,
       2, 2, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 1, 2, 2, 2, 0, 0, 2, 2, 2, 1,
       2, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0,
       0, 2, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 0, 2, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 2, 2, 2, 1,
       2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0,
       2, 2, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0, 0])

In [ ]:
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 1, 1, 2, 1, 1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2, 2, 1, 2,
       0, 2, 2, 2, 1, 0, 1, 1, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 1, 1, 1, 2,
       0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 0, 0, 0, 1,
       2, 1, 1, 2, 1, 1, 0, 2, 1, 1, 1, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 1,
       2, 0, 1, 1, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0,
       0, 2, 2, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 1,
       2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 0, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 0, 1, 0, 1, 1, 0,
       2, 2, 0, 2, 0, 0, 2, 1, 2, 0, 2, 2, 0, 0])

In [ ]:
classifier.predict_proba(x_test)

array([[9.49433818e-01, 3.91488130e-02, 1.14173692e-02],
       [5.12790143e-13, 1.00000000e+00, 1.05556278e-13],
       [7.89553566e-06, 9.99990691e-01, 1.41361755e-06],
       [1.31389117e-44, 7.32128996e-01, 2.67871004e-01],
       [2.81219645e-46, 3.41332879e-03, 9.96586671e-01],
       [1.01895517e-10, 1.00000000e+00, 1.91409946e-14],
       [3.19198579e-52, 9.99999994e-01, 5.78968651e-09],
       [9.59137959e-01, 4.06341238e-02, 2.27917418e-04],
       [4.80002283e-05, 9.99951798e-01, 2.01491007e-07],
       [3.87467632e-01, 3.25309936e-02, 5.80001374e-01],
       [1.42585515e-09, 9.99999990e-01, 8.18492530e-09],
       [3.41207699e-01, 3.97003504e-03, 6.54822266e-01],
       [6.61543194e-01, 1.24682449e-02, 3.25988561e-01],
       [3.41207699e-01, 3.97003504e-03, 6.54822266e-01],
       [7.82477816e-36, 1.00000000e+00, 4.95490707e-43],
       [3.19198579e-52, 9.99999994e-01, 5.78968651e-09],
       [9.89330022e-01, 1.03185088e-02, 3.51469067e-04],
       [1.31171908e-01, 1.02130

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[48  0  0]
 [ 3 75  0]
 [ 8  4 74]]


In [ ]:
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.81      1.00      0.90        48
           1       0.95      0.96      0.96        78
           2       1.00      0.86      0.92        86

    accuracy                           0.93       212
   macro avg       0.92      0.94      0.93       212
weighted avg       0.94      0.93      0.93       212



In [ ]:
akurasi = accuracy_score(y_test, y_pred)
print("Tingkat Akurasi : %d persen"%(akurasi*100))

Tingkat Akurasi : 92 persen


In [ ]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
ydata

y_test  y_pred
0         0       0
1         1       1
2         1       1
3         2       1
4         2       2
..      ...     ...
207       2       0
208       2       2
209       2       2
210       0       0
211       0       0

[212 rows x 2 columns]